-- Velora database: tables, view, triggers and sample data.
-- Migration file for Netlify Database. Place at:
-- netlify/database/migrations/20261004020000_create_velora.sql

CREATE TABLE IF NOT EXISTS site_settings (
  setting_key   VARCHAR(50) PRIMARY KEY,
  setting_value VARCHAR(255) NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS nav_links (
  link_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label      VARCHAR(40) NOT NULL,
  target     VARCHAR(60) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS car_models (
  model_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_name  VARCHAR(60) NOT NULL UNIQUE,
  body_color  CHAR(7) NOT NULL,
  description VARCHAR(255) NOT NULL,
  engine_type VARCHAR(10) NOT NULL CHECK (engine_type IN ('Petrol','Electric','Hybrid')),
  price_usd   NUMERIC(10,2) NOT NULL,
  view_count  INT NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS model_specs (
  spec_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id      INT NOT NULL UNIQUE REFERENCES car_models(model_id) ON DELETE CASCADE,
  power_hp      INT NOT NULL,
  top_speed_kmh INT NOT NULL,
  accel_0_100_s NUMERIC(3,1) NOT NULL,
  range_km      INT NOT NULL,
  power_pct     SMALLINT NOT NULL,
  speed_pct     SMALLINT NOT NULL,
  accel_pct     SMALLINT NOT NULL,
  range_pct     SMALLINT NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_pct CHECK (
    power_pct BETWEEN 0 AND 100 AND speed_pct BETWEEN 0 AND 100 AND
    accel_pct BETWEEN 0 AND 100 AND range_pct BETWEEN 0 AND 100)
);
CREATE TABLE IF NOT EXISTS features (
  feature_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       VARCHAR(60) NOT NULL,
  description VARCHAR(255) NOT NULL,
  sort_order  INT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS customers (
  customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name   VARCHAR(80) NOT NULL,
  email       VARCHAR(120) NOT NULL UNIQUE,
  phone       VARCHAR(25),
  city        VARCHAR(60),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS test_drive_bookings (
  booking_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INT NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
  model_id    INT NOT NULL REFERENCES car_models(model_id) ON DELETE CASCADE,
  drive_date  DATE NOT NULL,
  time_slot   VARCHAR(10) NOT NULL DEFAULT 'Sunset' CHECK (time_slot IN ('Morning','Afternoon','Sunset')),
  status      VARCHAR(10) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Confirmed','Completed','Cancelled')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_drive_date ON test_drive_bookings(drive_date);
CREATE TABLE IF NOT EXISTS interaction_log (
  log_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id       INT NOT NULL REFERENCES car_models(model_id) ON DELETE CASCADE,
  throttle_value SMALLINT NOT NULL CHECK (throttle_value BETWEEN 0 AND 100),
  speed_kmh      SMALLINT NOT NULL,
  action_type    VARCHAR(20) NOT NULL CHECK (action_type IN ('model_select','throttle_change')),
  logged_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_logged_at ON interaction_log(logged_at);

CREATE OR REPLACE VIEW v_model_spec_sheet AS
SELECT m.model_id, m.model_name, m.body_color, m.description, m.engine_type, m.price_usd, m.view_count,
       s.power_hp, s.top_speed_kmh, s.accel_0_100_s, s.range_km,
       s.power_pct, s.speed_pct, s.accel_pct, s.range_pct
FROM car_models m
JOIN model_specs s ON s.model_id = m.model_id
WHERE m.is_active = TRUE;

CREATE OR REPLACE FUNCTION fn_set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_settings_updated ON site_settings;
CREATE TRIGGER trg_settings_updated BEFORE UPDATE ON site_settings
FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

DROP TRIGGER IF EXISTS trg_specs_updated ON model_specs;
CREATE TRIGGER trg_specs_updated BEFORE UPDATE ON model_specs
FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE OR REPLACE FUNCTION fn_increment_views() RETURNS trigger AS $$
BEGIN
  IF NEW.action_type = 'model_select' THEN
    UPDATE car_models SET view_count = view_count + 1 WHERE model_id = NEW.model_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_log_increment_views ON interaction_log;
CREATE TRIGGER trg_log_increment_views AFTER INSERT ON interaction_log
FOR EACH ROW EXECUTE FUNCTION fn_increment_views();

INSERT INTO site_settings (setting_key, setting_value) VALUES
('brand_name',    'VELORA'),
('hero_title',    'Chase the golden hour.'),
('hero_subtitle', 'Three machines tuned for long coastal roads at sunset. Slide the throttle, pick a model, and watch the road respond.'),
('why_title',     'Built for the long way home'),
('footer_left',   '© 2026 Velora Motors. Demo page.'),
('footer_right',  'Drive safe. Enjoy the sunset.')
ON CONFLICT (setting_key) DO NOTHING;

INSERT INTO nav_links (label, target, sort_order) VALUES
('Specs', '#specs', 1),
('Why Velora', '#why', 2);

INSERT INTO car_models (model_name, body_color, description, engine_type, price_usd) VALUES
('Vela Coupe',  '#ff4d8d', 'A two-door grand tourer with a throaty V8 and a body that looks fast standing still.', 'Petrol',   145000.00),
('Lumen EV',    '#2ee6c5', 'Silent, instant torque and a battery built for a full day of coastal driving.',        'Electric',  98000.00),
('Orion Hyper', '#ffb02e', 'A track-bred hypercar with active aero and a launch that pins you to the seat.',       'Hybrid',   320000.00);

INSERT INTO model_specs (model_id, power_hp, top_speed_kmh, accel_0_100_s, range_km, power_pct, speed_pct, accel_pct, range_pct)
SELECT model_id, 520, 300, 3.9, 650, 75, 88, 80, 62 FROM car_models WHERE model_name = 'Vela Coupe'
UNION ALL
SELECT model_id, 480, 250, 3.2, 720, 68, 74, 92, 90 FROM car_models WHERE model_name = 'Lumen EV'
UNION ALL
SELECT model_id, 900, 380, 2.4, 420, 100, 100, 100, 45 FROM car_models WHERE model_name = 'Orion Hyper';

INSERT INTO features (title, description, sort_order) VALUES
('Quiet cabin', 'Layered glass and tuned airflow keep wind noise low, so the road is all you hear.', 1),
('Adaptive suspension', 'The chassis reads the surface every millisecond and softens bumps before you feel them.', 2),
('Night-ready lights', 'Matrix headlights shape the beam around other cars and light every curve ahead.', 3);

INSERT INTO customers (full_name, email, phone, city) VALUES
('Ezaz Khan',    'ezaz@example.com',   '0300-1111111', 'Karachi'),
('Ayesha Malik', 'ayesha@example.com', '0301-2222222', 'Lahore'),
('Hamza Ali',    'hamza@example.com',  '0302-3333333', 'Islamabad'),
('Sara Ahmed',   'sara@example.com',   '0303-4444444', 'Karachi');

INSERT INTO test_drive_bookings (customer_id, model_id, drive_date, time_slot, status)
SELECT c.customer_id, m.model_id, d.drive_date::date, d.slot, d.status
FROM (VALUES
  ('ezaz@example.com',   'Vela Coupe',  '2026-10-10', 'Sunset',    'Confirmed'),
  ('ayesha@example.com', 'Lumen EV',    '2026-10-11', 'Morning',   'Pending'),
  ('hamza@example.com',  'Orion Hyper', '2026-10-12', 'Afternoon', 'Pending'),
  ('sara@example.com',   'Lumen EV',    '2026-10-15', 'Sunset',    'Completed')
) AS d(email, model, drive_date, slot, status)
JOIN customers c ON c.email = d.email
JOIN car_models m ON m.model_name = d.model;
