-- =====================================================================
--  VELORA MOTORS DATABASE  (PostgreSQL / Netlify Database)
--  Run as a full SCRIPT (DBeaver: Alt+X, psql: -f postgres.sql).
--  Can also be used as a Netlify migration file:
--  netlify/database/migrations/20261003000000_create_velora.sql
-- =====================================================================

-- Clean start (only Velora's own objects)
DROP VIEW     IF EXISTS v_model_spec_sheet;
DROP TABLE    IF EXISTS interaction_log     CASCADE;
DROP TABLE    IF EXISTS test_drive_bookings CASCADE;
DROP TABLE    IF EXISTS customers           CASCADE;
DROP TABLE    IF EXISTS features            CASCADE;
DROP TABLE    IF EXISTS model_specs         CASCADE;
DROP TABLE    IF EXISTS car_models          CASCADE;
DROP TABLE    IF EXISTS nav_links           CASCADE;
DROP TABLE    IF EXISTS site_settings       CASCADE;
DROP FUNCTION IF EXISTS fn_set_updated_at()  CASCADE;
DROP FUNCTION IF EXISTS fn_increment_views() CASCADE;

-- 1. site_settings : texts shown on the page
CREATE TABLE site_settings (
    setting_key   VARCHAR(50)  PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- 2. nav_links : top navigation items
CREATE TABLE nav_links (
    link_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label      VARCHAR(40) NOT NULL,
    target     VARCHAR(60) NOT NULL,
    sort_order INT         NOT NULL DEFAULT 0,
    is_active  BOOLEAN     NOT NULL DEFAULT TRUE
);

-- 3. car_models : the three model chips
CREATE TABLE car_models (
    model_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name  VARCHAR(60)   NOT NULL UNIQUE,
    body_color  CHAR(7)       NOT NULL,
    description VARCHAR(255)  NOT NULL,
    engine_type VARCHAR(10)   NOT NULL CHECK (engine_type IN ('Petrol','Electric','Hybrid')),
    price_usd   NUMERIC(10,2) NOT NULL,
    view_count  INT           NOT NULL DEFAULT 0,
    is_active   BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- 4. model_specs : the four animated bars
CREATE TABLE model_specs (
    spec_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id       INT          NOT NULL UNIQUE REFERENCES car_models(model_id) ON DELETE CASCADE,
    power_hp       INT          NOT NULL,
    top_speed_kmh  INT          NOT NULL,
    accel_0_100_s  NUMERIC(3,1) NOT NULL,
    range_km       INT          NOT NULL,
    power_pct      SMALLINT     NOT NULL,
    speed_pct      SMALLINT     NOT NULL,
    accel_pct      SMALLINT     NOT NULL,
    range_pct      SMALLINT     NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_pct CHECK (
        power_pct BETWEEN 0 AND 100 AND speed_pct BETWEEN 0 AND 100 AND
        accel_pct BETWEEN 0 AND 100 AND range_pct BETWEEN 0 AND 100)
);

-- 5. features : the three columns in "Built for the long way home"
CREATE TABLE features (
    feature_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(60)  NOT NULL,
    description VARCHAR(255) NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 0
);

-- 6. customers
CREATE TABLE customers (
    customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(80)  NOT NULL,
    email       VARCHAR(120) NOT NULL UNIQUE,
    phone       VARCHAR(25),
    city        VARCHAR(60),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- 7. test_drive_bookings
CREATE TABLE test_drive_bookings (
    booking_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT         NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
    model_id    INT         NOT NULL REFERENCES car_models(model_id)   ON DELETE CASCADE,
    drive_date  DATE        NOT NULL,
    time_slot   VARCHAR(10) NOT NULL DEFAULT 'Sunset'  CHECK (time_slot IN ('Morning','Afternoon','Sunset')),
    status      VARCHAR(10) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Confirmed','Completed','Cancelled')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_drive_date ON test_drive_bookings(drive_date);

-- 8. interaction_log : every model click / throttle move on the page
CREATE TABLE interaction_log (
    log_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id       INT         NOT NULL REFERENCES car_models(model_id) ON DELETE CASCADE,
    throttle_value SMALLINT    NOT NULL CHECK (throttle_value BETWEEN 0 AND 100),
    speed_kmh      SMALLINT    NOT NULL,
    action_type    VARCHAR(20) NOT NULL CHECK (action_type IN ('model_select','throttle_change')),
    logged_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_logged_at ON interaction_log(logged_at);

-- VIEW : one ready-to-use row per active model
CREATE VIEW v_model_spec_sheet AS
SELECT m.model_id, m.model_name, m.body_color, m.description, m.engine_type, m.price_usd, m.view_count,
       s.power_hp, s.top_speed_kmh, s.accel_0_100_s, s.range_km,
       s.power_pct, s.speed_pct, s.accel_pct, s.range_pct
FROM car_models m
JOIN model_specs s ON s.model_id = m.model_id
WHERE m.is_active = TRUE;

-- FUNCTION + TRIGGERS : keep updated_at fresh
CREATE FUNCTION fn_set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_settings_updated BEFORE UPDATE ON site_settings
FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER trg_specs_updated BEFORE UPDATE ON model_specs
FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- FUNCTION + TRIGGER : model_select logged -> increase that model's view_count
CREATE FUNCTION fn_increment_views() RETURNS trigger AS $$
BEGIN
    IF NEW.action_type = 'model_select' THEN
        UPDATE car_models SET view_count = view_count + 1 WHERE model_id = NEW.model_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_log_increment_views AFTER INSERT ON interaction_log
FOR EACH ROW EXECUTE FUNCTION fn_increment_views();

-- =====================================================================
--  SAMPLE DATA
-- =====================================================================
INSERT INTO site_settings (setting_key, setting_value) VALUES
('brand_name',     'VELORA'),
('hero_title',     'Chase the golden hour.'),
('hero_subtitle',  'Three machines tuned for long coastal roads at sunset. Slide the throttle, pick a model, and watch the road respond.'),
('why_title',      'Built for the long way home'),
('footer_left',    '© 2026 Velora Motors. Demo page.'),
('footer_right',   'Drive safe. Enjoy the sunset.');

INSERT INTO nav_links (label, target, sort_order) VALUES
('Specs',      '#specs', 1),
('Why Velora', '#why',   2);

INSERT INTO car_models (model_name, body_color, description, engine_type, price_usd) VALUES
('Vela Coupe',  '#ff4d8d', 'A two-door grand tourer with a throaty V8 and a body that looks fast standing still.', 'Petrol',   145000.00),
('Lumen EV',    '#2ee6c5', 'Silent, instant torque and a battery built for a full day of coastal driving.',        'Electric',  98000.00),
('Orion Hyper', '#ffb02e', 'A track-bred hypercar with active aero and a launch that pins you to the seat.',       'Hybrid',   320000.00);

INSERT INTO model_specs (model_id, power_hp, top_speed_kmh, accel_0_100_s, range_km, power_pct, speed_pct, accel_pct, range_pct) VALUES
(1, 520, 300, 3.9, 650,  75,  88,  80,  62),
(2, 480, 250, 3.2, 720,  68,  74,  92,  90),
(3, 900, 380, 2.4, 420, 100, 100, 100,  45);

INSERT INTO features (title, description, sort_order) VALUES
('Quiet cabin',         'Layered glass and tuned airflow keep wind noise low, so the road is all you hear.',       1),
('Adaptive suspension', 'The chassis reads the surface every millisecond and softens bumps before you feel them.', 2),
('Night-ready lights',  'Matrix headlights shape the beam around other cars and light every curve ahead.',         3);

INSERT INTO customers (full_name, email, phone, city) VALUES
('Ezaz Khan',    'ezaz@example.com',   '0300-1111111', 'Karachi'),
('Ayesha Malik', 'ayesha@example.com', '0301-2222222', 'Lahore'),
('Hamza Ali',    'hamza@example.com',  '0302-3333333', 'Islamabad'),
('Sara Ahmed',   'sara@example.com',   '0303-4444444', 'Karachi');

INSERT INTO test_drive_bookings (customer_id, model_id, drive_date, time_slot, status) VALUES
(1, 1, '2026-10-10', 'Sunset',    'Confirmed'),
(2, 2, '2026-10-11', 'Morning',   'Pending'),
(3, 3, '2026-10-12', 'Afternoon', 'Pending'),
(4, 2, '2026-10-15', 'Sunset',    'Completed');

INSERT INTO interaction_log (model_id, throttle_value, speed_kmh, action_type) VALUES
(1,  55, 132, 'model_select'),
(1,  80, 192, 'throttle_change'),
(2,  55, 132, 'model_select'),
(3,  95, 228, 'model_select'),
(3, 100, 240, 'throttle_change'),
(2,  40,  96, 'model_select');

-- =====================================================================
--  TEST QUERIES (run one at a time after the script above)
-- =====================================================================

-- A) Everything the spec section needs
SELECT * FROM v_model_spec_sheet;

-- B) Page texts
SELECT setting_key, setting_value FROM site_settings;

-- C) Most viewed model (trigger already counted the sample clicks)
SELECT model_name, view_count FROM car_models ORDER BY view_count DESC;

-- D) Bookings with customer and model names
SELECT b.booking_id, c.full_name, c.city, m.model_name, b.drive_date, b.time_slot, b.status
FROM test_drive_bookings b
JOIN customers  c ON c.customer_id = b.customer_id
JOIN car_models m ON m.model_id    = b.model_id
ORDER BY b.drive_date;

-- ---------------------------------------------------------------------
--  DYNAMIC UPDATE TEST: run a step, then re-run its SELECT
-- ---------------------------------------------------------------------

-- Step 1: a visitor clicks "Orion Hyper" (trigger fires)
INSERT INTO interaction_log (model_id, throttle_value, speed_kmh, action_type) VALUES (3, 70, 168, 'model_select');
SELECT model_name, view_count FROM car_models ORDER BY model_id;

-- Step 2: change a spec (updated_at refreshes automatically)
UPDATE model_specs SET power_hp = 950, power_pct = 100 WHERE model_id = 3;
SELECT m.model_name, s.power_hp, s.updated_at
FROM model_specs s JOIN car_models m ON m.model_id = s.model_id
WHERE s.model_id = 3;

-- Step 3: change the hero headline
UPDATE site_settings SET setting_value = 'Drive into the sunset.' WHERE setting_key = 'hero_title';
SELECT * FROM site_settings WHERE setting_key = 'hero_title';

-- Step 4: add a booking and confirm it
INSERT INTO test_drive_bookings (customer_id, model_id, drive_date, time_slot) VALUES (1, 3, '2026-10-20', 'Sunset');
UPDATE test_drive_bookings SET status = 'Confirmed'
WHERE booking_id = (SELECT MAX(booking_id) FROM test_drive_bookings);
SELECT booking_id, status, drive_date FROM test_drive_bookings ORDER BY booking_id DESC LIMIT 1;

-- Step 5: add a brand-new car model with its specs
INSERT INTO car_models (model_name, body_color, description, engine_type, price_usd)
VALUES ('Nova Roadster', '#7c9cff', 'A light open-top roadster made for twisting mountain roads.', 'Petrol', 87000.00);
INSERT INTO model_specs (model_id, power_hp, top_speed_kmh, accel_0_100_s, range_km, power_pct, speed_pct, accel_pct, range_pct)
VALUES ((SELECT model_id FROM car_models WHERE model_name = 'Nova Roadster'), 400, 270, 4.3, 560, 55, 80, 70, 55);
SELECT model_name, body_color, power_hp FROM v_model_spec_sheet;

-- Step 6: hide that model from the site without deleting it
UPDATE car_models SET is_active = FALSE WHERE model_name = 'Nova Roadster';
SELECT model_name FROM v_model_spec_sheet;
